AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora Serverless v2 (Aurora3)
Parameters:
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
  VpcRdsSubnetIds:
    Description: RDS VPC subnets list
    Type: List<AWS::EC2::Subnet::Id>
  DbClientCidr:
    Description: DB Client CIDR Block
    Type: String
    Default: 172.31.0.0/16
  RdsDBClusterIdentifier:
    Description: DBClusterIdentifier
    Type: String
    Default: aurora-sl-v2
  MasterUsername:
    Description: MasterUsername
    Type: String
    Default: fcsadmin
  MasterUserPassword:
    Description: MasterUserPassword
    Type: String
    Default: fcspassword
    NoEcho: true
  DatabaseName:
    Description: DatabaseName
    Type: String
    Default: testdb

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${AWS::StackName}-DBSubnetGroup'
      SubnetIds: !Ref 'VpcRdsSubnetIds'

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcId'
      GroupDescription: !Sub '${AWS::StackName}-Allow PostgreSQL-(tcp5432)'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref 'DbClientCidr'

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub '${AWS::StackName}-DBClusterParameterGroup'
      Family: aurora-postgresql13
      Parameters:
      # DBクラスターパラメータはこちらのサイトを参考（https://aws.amazon.com/jp/blogs/news/deploy-an-amazon-aurora-postgresql-db-cluster-with-recommended-best-practices-using-aws-cloudformation/）
        timezone: Asia/Tokyo
        rds.force_ssl: 1

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub '${AWS::StackName}-DBParameterGroup'
      # Family: aurora-mysql8.0
      Family: aurora-postgresql13
      Parameters:
      # DBクラスターパラメータはこちらのサイトを参考（https://aws.amazon.com/jp/blogs/news/deploy-an-amazon-aurora-postgresql-db-cluster-with-recommended-best-practices-using-aws-cloudformation/）
        log_connections: 1

  DBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties:
      DBSubnetGroupName: !Ref 'DBSubnetGroup'
      Engine: aurora-postgresql
      EngineVersion: 13.7
      VpcSecurityGroupIds:
        - !Ref 'SecurityGroup'
      DBClusterParameterGroupName: !Ref 'DBClusterParameterGroup'
      PreferredMaintenanceWindow: Thu:18:35-Thu:19:05
      PreferredBackupWindow: 18:05-18:35
      BackupRetentionPeriod: 7
      DatabaseName: !Ref 'DatabaseName'
      MasterUsername: !Ref 'MasterUsername'
      MasterUserPassword: !Ref 'MasterUserPassword'
      ServerlessV2ScalingConfiguration:
        MaxCapacity: 16
        MinCapacity: 2

  DBInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref 'DBCluster'
      DBInstanceClass: db.serverless
      DBParameterGroupName: !Ref 'DBParameterGroup'
      Engine: aurora-postgresql
      EnablePerformanceInsights: true
      PreferredMaintenanceWindow: Thu:19:05-Thu:19:35
      PromotionTier: 0
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region

  # DBInstance2:
  #   Type: AWS::RDS::DBInstance
  #   Properties:
  #     DBClusterIdentifier: !Ref 'DBCluster'
  #     DBInstanceClass: db.serverless
  #     DBParameterGroupName: !Ref 'DBParameterGroup'
  #     # Engine: aurora-mysql
  #     Engine: aurora-postgresql
  #     EnablePerformanceInsights: true
  #     PreferredMaintenanceWindow: Thu:19:05-Thu:19:35
  #     PromotionTier: 1
  #     AvailabilityZone: !Select
  #       - 1
  #       - !GetAZs
  #         Ref: AWS::Region